### ISSUE TITLE
What's y_center and diag_max in fitting_3D_mesh.py?

### ISSUE THREAD

**Issue by SJoJoK** [liren2515/ISP#1]
Hello, thanks for your amazing work.

I want to fit my own 3D scan of clothes, and I notice that I should provide `y_center` and `diag_max` of the 3D Scan. Based on the literal meaning, these two variables seem to represent the center value of the y-coordinates of all vertices and the length of the diagonal of the bounding box. However, upon examining the data, I found that this is not the case. Could you please clarify what these two variables represent? Or, what assumptions does ISP require for the input 3D scans?

Thanks in advance for any help of advice.

**Comment by SJoJoK** [comment]
Oh, I might discovere the reason for the inconsistency between the literal meaning and the actual data. I used 'tee' for testing, but this line (https://github.com/liren2515/ISP/blob/74c40c9ce9a7706eab38f9bfc87a9abee1c24532/fitting_3D_mesh.py#L24C66-L24C66) is incorrect. However, I'd still appreciate clarification on the requirements for the input 3D scans, thanks.

**Comment by liren2515** [comment]
Yes, it should work.

**Comment by SJoJoK** [comment]
got it, thanks---- Replied Message ----FromRen ***@***.***>Date11/30/2023 22:40 ***@***.***> CcJac ***@***.***>***@***.***>SubjectRe: [liren2515/ISP] What's y_center and diag_max in fitting_3D_mesh.py? (Issue #1)
Yes, it should work.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/liren2515/ISP/issues/1#issuecomment-1833904872",
"url": "https://github.com/liren2515/ISP/issues/1#issuecomment-1833904872",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
