### ISSUE TITLE
Get the cloth obj in SMPL canonical space

### ISSUE THREAD

**Issue by Pbb-land** [liren2515/ISP#2]
Hello, thanks for your amazing work.

I want to fit the clothes from the images, so I ran fitting_image.py and get the posed clothes mesh. How can I get these mesh in canonical space or get the blend weight, posedirs and shapedirs of these meshes?

**Comment by liren2515** [comment]
When you run `fitting_image.py`, you will have the fitted latent codes for the garment like `/best-z-fit-0.pt`, `/best-z-fit-1.pt` and `/best-z-fit-2.pt` in [here](https://github.com/liren2515/ISP/blob/74c40c9ce9a7706eab38f9bfc87a9abee1c24532/fitting_image.py#L221C48-L221C64). These codes encode the garment in canonical space. You can use them to reconstruct the mesh using the code of `infer_isp.py`. What you need to do is changing the latent code in [this line](https://github.com/liren2515/ISP/blob/74c40c9ce9a7706eab38f9bfc87a9abee1c24532/infer_isp.py#L99C11-L99C11) with those .pt files.
